# Defining characters
define n = Character(None)
define m = Character("Masami", image = "masami")
define p = Character("Principal")
define mm = Character("Masami's Mother")
define s = Character("Sabie", image = "sabie")
define r = Character("Rohan", image = "rohan")
define t = Character("Tyree", image = "tyree")
define a = Character("Alyssa")
define na = Character("Nasir", image = "nasir")
define md = Character("Masami's Father")
define fa = Character("Alyssa’s Friend 1")
define fb= Character("Alyssa’s Friend 2")
define ca = Character("Store Cashier")
define x = Character("Xinyi", image = "xinyi")
define u = Character("???")
